[project]
name = "huggingface-collection"
version = "0.1.0"
description = "HuggingFace model collection and research"
readme = "README.md"
requires-python = ">=3.12"
authors = [
    { name = "aiseed", email = "aiseed@aiseed.kr" }
]

dependencies = [
    "numpy>=2.0.0",
    "tqdm>=4.66.0",
    "ipykernel>=6.29.5",
    "ruff>=0.14.8",
    "python-dotenv>=1.2.1",
    "pyyaml>=6.0.3",
    "torch==2.9.1",
    "torchvision==0.24.1",
    "transformers==4.56.1",
    "datasets>=4.0.0",
    "bitsandbytes>=0.46.1",
    "accelerate>=1.9.0",
    "peft>=0.17.1",
    "math-verify>=0.9.0",
    "unsloth>=2026.1.4",
    "mlflow>=3.9.0",
    "unsloth-zoo>=2026.1.4",
    "trl==0.19.1",
    "gradio>=6.5.1",
    "ollama>=0.6.1",
]

[dependency-groups]
analysis = [
    "pandas>=2.2.0",
    "matplotlib>=3.9.0",
    "seaborn>=0.13.0",
    "scipy>=1.13.0",
]
ml = [
    "torch==2.9.1",
    "torchvision==0.24.1",
    "mlflow>=3.9.0",
    "gradio>=6.5.1",
]
llm = [
    "transformers==4.56.1",
    "datasets>=4.0.0",
    "bitsandbytes>=0.46.1",
    "accelerate>=1.9.0",
    "peft>=0.17.1",
    "trl==0.19.1",
    "ollama>=0.6.1",
]

[tool.pytest.ini_options]
pythonpath = "src"
addopts = ["--import-mode=importlib"]
log_cli = true
log_cli_level = "DEBUG"
log_cli_date_format = "%Y-%m-%dT%H:%M:%S%z"
log_cli_format = "%(levelname)-8s %(asctime)s %(name)s:%(funcName)s:L%(lineno)d %(message)s"

[tool.uv.sources]
torch = [
  { index = "pytorch-cu128", marker = "sys_platform != 'darwin'" },
  { index = "pytorch-cpu", marker = "sys_platform == 'darwin'" },
]
torchvision = [
  { index = "pytorch-cu128", marker = "sys_platform != 'darwin'" },
  { index = "pytorch-cpu", marker = "sys_platform == 'darwin'" },
]

[[tool.uv.index]]
name = "pytorch-cu128"
url = "https://download.pytorch.org/whl/cu128"
explicit = true

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true
